import type { SoundKind } from '../simulation/sound';
export type AudioCue = SoundKind | 'click';
export interface SoundDefinition { files: string[]; gain: number; interval: number; rate?: number; duration?: number }

// Sources, original filenames and licenses are recorded in public/audio/sfx.
export const SOUND_LIBRARY: Record<AudioCue, SoundDefinition> = {
  'boss-arrival':{files:['giant-1.wav'],gain:.38,interval:4,rate:.72,duration:1.8},
  'boss-windup':{files:['charge.wav'],gain:.30,interval:2,rate:.8,duration:1.4},
  'boss-slam':{files:['earth-burst.wav'],gain:.42,interval:1,rate:.85,duration:1.3},
  'boss-rage':{files:['giant-2.wav'],gain:.38,interval:8,rate:.78,duration:1.6},
  'boss-death':{files:['giant-5.wav'],gain:.38,interval:3,rate:.7,duration:1.8},
  'cannon':{files:['cannon-fire.ogg'],gain:0.33,interval:0.22,rate:1,duration:0.8},
  'explosion':{files:['shell-impact.wav'],gain:0.3,interval:0.22,rate:1,duration:0.95},
  'frost':{files:['ice-wind.wav'],gain:0.23,interval:0.2,rate:1,duration:0.65},
  'thunder':{files:['electric-cast.wav'],gain:.34,interval:0.25,rate:1,duration:0.65},
  'bow-heavy':{files:['bow-heavy.wav'],gain:0.28,interval:0.12,rate:1,duration:1},
  'bow-volley':{files:['swing-1.wav', 'swing-2.wav'],gain:0.40,interval:0.09,rate:1.25,duration:.35},
  'fire-cast':{files:['flame-cast.wav'],gain:0.22,interval:0.23,rate:1,duration:0.65},
  'fire-hit':{files:['flame-impact.wav'],gain:0.22,interval:0.3,rate:1,duration:1.1},
  'arcane-cast':{files:['energy-surge.wav'],gain:0.2,interval:0.2,rate:1,duration:0.5},
  'arcane-hit':{files:['energy-impact.wav'],gain:0.24,interval:0.2,rate:0.9,duration:0.6},
  'mortar':{files:['cannon-fire.ogg'],gain:0.32,interval:0.28,rate:0.78,duration:1},
  'mortar-hit':{files:['mortar-impact.wav', 'siege-impact.wav'],gain:0.36,interval:0.3,rate:1,duration:1.6},
  'missile':{files:['energy-surge.wav'],gain:0.35,interval:0.25,rate:1,duration:0.7},
  'missile-hit':{files:['energy-impact.wav'],gain:0.34,interval:0.22,rate:1,duration:1},
  'blizzard':{files:['ice-wind.wav'],gain:0.18,interval:0.3,rate:0.9,duration:0.9},
  'blizzard-hit':{files:['ice-crush.wav'],gain:0.23,interval:0.25,rate:1,duration:0.5},
  'glacier':{files:['ice-wind.wav'],gain:0.2,interval:0.25,rate:0.8,duration:0.8},
  'glacier-hit':{files:['ice-crack.wav'],gain:0.29,interval:0.22,rate:0.9,duration:0.9},
  'ice-hit':{files:['ice-crack.wav'],gain:0.21,interval:0.22,rate:1,duration:0.8},
  'lightning-hit':{files:['electric-crack.wav'],gain:.31,interval:0.2,rate:1,duration:0.45},
  'chain-lightning':{files:['electric-cast.wav'],gain:.35,interval:0.2,rate:1,duration:0.65},
  'judgment':{files:['thunder-burst.wav'],gain:.58,interval:0.3,rate:1,duration:.55},
  'hero-arrow':{files:['swing-2.wav'],gain:0.24,interval:0.13,rate:0.95,duration:0.5},
  'hero-hit':{files:['metal-light.ogg'],gain:0.2,interval:0.12,rate:1.2,duration:0.5},
  'hero-rapier':{files:['rapier-1.wav', 'rapier-2.wav'],gain:0.28,interval:0.15,rate:1,duration:1},
  'hero-flight':{files:['wing-wind.wav'],gain:0.25,interval:0.5,rate:1,duration:1.74},
  'hero-land':{files:['ice-wind.wav'],gain:0.12,interval:0.4,rate:0.85,duration:0.6},
  'hero-piercing':{files:['energy-surge.wav'],gain:0.26,interval:0.5,rate:1,duration:0.5},
  'hero-rain':{files:['energy-cast.wav'],gain:0.2,interval:0.5,rate:0.85,duration:0.6},
  'hero-rain-hit':{files:['energy-impact.wav'],gain:0.17,interval:.12,rate:1,duration:0.45},
  'hero-gale':{files:['ice-wind.wav'],gain:0.22,interval:0.6,rate:0.75,duration:0.85},
  'hero-skill-hit':{files:['energy-impact.wav'],gain:0.22,interval:0.3,rate:0.8,duration:0.55},
  'hero-fall':{files:['magic-death.wav'],gain:0.27,interval:1,rate:1,duration:2.5},
  'hero-arrival':{files:['holy-breath.wav'],gain:0.17,interval:1,rate:0.8,duration:1.3},
  'soldier-fall':{files:['armor-fall.wav'],gain:0.22,interval:0.3,rate:1,duration:1},
  'soldier-sword':{files:['blade-cut.wav', 'sword.wav'],gain:0.22,interval:0.12,rate:1,duration:0.65},
  'spellblade-cast':{files:['energy-cast.wav'],gain:0.22,interval:.22,rate:1,duration:0.6},
  'spellblade-hit':{files:['electric-crack.wav'],gain:0.2,interval:.16,rate:0.9,duration:0.4},
  'spellblade-slash':{files:['blade-enchanted.wav'],gain:0.25,interval:.14,rate:1,duration:0.6},
  'paladin-sword':{files:['metal-heavy.ogg','sword.wav'],gain:0.26,interval:.15,rate:.9,duration:.8},
  'paladin-block':{files:['shield-block.wav'],gain:0.23,interval:.3,rate:1,duration:0.65},
  'paladin-sanctuary':{files:['holy-breath.wav'],gain:0.22,interval:1,rate:0.8,duration:1.3},
  'goblin-attack':{files:['mnstr-1.wav', 'mnstr-2.wav'],gain:0.14,interval:0.32,rate:1,duration:1},
  'goblin-death':{files:['mnstr-3.wav', 'mnstr-4.wav'],gain:0.17,interval:0.32,rate:1,duration:1},
  'runner-attack':{files:['ogre-1.wav', 'ogre-2.wav'],gain:0.13,interval:0.3,rate:1.35,duration:1},
  'runner-death':{files:['ogre-4.wav', 'ogre-5.wav'],gain:0.16,interval:0.3,rate:1.3,duration:1},
  'brute-attack':{files:['giant-1.wav', 'giant-2.wav'],gain:0.19,interval:0.4,rate:1,duration:1},
  'brute-death':{files:['giant-4.wav', 'giant-5.wav'],gain:0.22,interval:0.4,rate:1,duration:1},
  'ironclad-attack':{files:['metal-heavy.ogg'],gain:0.24,interval:0.25,rate:1,duration:0.7},
  'ironclad-death':{files:['armor-fall.wav', 'metal-heavy.ogg'],gain:0.28,interval:0.35,rate:0.8,duration:1},
  'runeguard-attack':{files:['energy-surge.wav'],gain:0.19,interval:0.3,rate:0.8,duration:0.6},
  'runeguard-death':{files:['shade-4.wav', 'shade-5.wav'],gain:0.19,interval:0.35,rate:0.85,duration:1},
  'marshling-attack':{files:['slime-1.wav', 'slime-2.wav'],gain:0.19,interval:0.3,rate:1,duration:1},
  'marshling-death':{files:['slime-7.wav', 'slime-8.wav', 'water-burst.wav'],gain:0.19,interval:0.35,rate:1,duration:1},
  'hexer-attack':{files:['energy-cast.wav'],gain:0.17,interval:0.35,rate:0.72,duration:0.65},
  'hexer-death':{files:['shade-10.wav', 'shade-11.wav'],gain:0.19,interval:0.35,rate:1,duration:1.3},
  'gargoyle-attack':{files:['mnstr-6.wav', 'mnstr-8.wav'],gain:0.17,interval:0.3,rate:0.85,duration:1},
  'gargoyle-death':{files:['mnstr-10.wav', 'mnstr-11.wav'],gain:0.19,interval:0.35,rate:0.85,duration:1},
  'enemy-magic-hit':{files:['energy-impact.wav'],gain:0.17,interval:0.3,rate:0.85,duration:0.6},
  arrow: { files:['swing-1.wav','swing-2.wav'], gain:.46, interval:.08, rate:1.15, duration:.35 },
  cast:{files:['energy-cast.wav'],gain:0.23,interval:.13,rate:1,duration:0.6},
  impact: { files:['soft-hit.ogg','light-hit.ogg'], gain:.30, interval:.08 },
  'magic-hit':{files:['energy-impact.wav'],gain:0.23,interval:.16,rate:1,duration:0.55},
  death: { files:['monster.wav'], gain:.17, interval:.23, duration:.8 },
  melee: { files:['sword.wav','metal-hit.ogg','punch-heavy.ogg'], gain:.24, interval:.09, duration:.65 },
  'wall-hit': { files:['mining.ogg','mining-2.ogg'], gain:.38, interval:.12 },
  collapse: { files:['wood-heavy.ogg','wood-heavy-2.ogg'], gain:.47, interval:.18, rate:.8 },
  'castle-hit': { files:['wood-heavy-2.ogg'], gain:.50, interval:.24, rate:.72 },
  dig: { files:['mining.ogg','mining-2.ogg'], gain:.30, interval:.12 },
  splash: { files:['water.wav'], gain:.17, interval:.25, duration:.6 },
  raise: { files:['mining-2.ogg'], gain:.32, interval:.12 },
  build: { files:['chop.ogg','wood-medium.ogg'], gain:.32, interval:.1 },
  upgrade: { files:['coins.ogg'], gain:.22, interval:.2, duration:.9 },
  error: { files:['latch.ogg'], gain:.22, interval:.2, rate:.8 },
  recruit: { files:['armor.ogg'], gain:.16, interval:.3 },
  wave: { files:['bell.ogg'], gain:.42, interval:.7, rate:.72, duration:2 },
  'wave-clear': { files:['bell-2.ogg'], gain:.28, interval:.7, rate:1.05 },
  victory: { files:['notification.wav'], gain:.34, interval:1, duration:1.4 },
  defeat: { files:['bell.ogg'], gain:.36, interval:1, rate:.55, duration:1.7 },
  click: { files:['click.ogg'], gain:.18, interval:.06 },
};
export const SOUND_FILES = [...new Set(Object.values(SOUND_LIBRARY).flatMap(s=>s.files))];
export const UI_CUES = new Set<AudioCue>(['click','wave','wave-clear','victory','defeat','error','upgrade','build','dig','raise']);
