import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
// macOS Codex Seatbelt denies Chromium Mach service registration on this Mac.
// Stop before spawning a browser so the test does not trigger a crash dialog.
if (process.platform === 'darwin' && process.env.CODEX_SANDBOX === 'seatbelt') {
 console.error('Browser test stopped before launch: this macOS Codex sandbox blocks Chromium Mach service registration. Use the connected browser tool, or run this test in your normal Terminal / an approved browser-capable execution environment.');
 process.exit(2);
}

await fs.mkdir('.playwright',{recursive:true});
const browser = await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {}),headless:true,args:['--use-angle=metal']});
const checks=[];
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.addInitScript(()=>localStorage.removeItem('riverwatch.bestiary.v1'));
  await page.goto('about:blank');
  console.log(JSON.stringify({chromeLaunch:'passed',version:browser.version()}));
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
  await page.getByRole('button',{name:'进入大陆',exact:true}).click({timeout:180000});
  await page.waitForFunction(()=>window.__riverwatch?.world.renderer.info.render.calls>0);
  await page.screenshot({path:'.playwright/desktop.png'});
  checks.push('WebGL scene boots and renders');
  assert.equal(await page.evaluate(()=>window.__riverwatch.snapshot().screen),'campaign');
  assert.equal(await page.locator('.atlas-journey').count(),0);
  assert.equal(await page.locator('.atlas-card').isVisible(),false);
  await page.locator('.atlas-pin').click();
  assert.equal(await page.locator('.atlas-card').isVisible(),true);
  assert.equal(await page.locator('#atlas-thumbnail').isVisible(),true);
  await page.locator('#atlas-deploy').click();
  await page.waitForFunction(()=>!window.__riverwatch.travel.active&&window.__riverwatch.snapshot().screen==='battle');
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.mapId),'windford');
  assert.deepEqual(await page.evaluate(()=>window.__riverwatch.snapshot().map),[100,80]);
  assert.deepEqual(await page.evaluate(()=>Object.keys(window.__riverwatch.game.resources)),['gold']);
  assert.equal(await page.locator('#wood, #stone').count(),0);
  assert.ok((await page.locator('[data-tool=archer] small').textContent()).includes('75 金币'));
  const placementCell=await page.evaluate(()=>{
    const {game,world}=window.__riverwatch;
    return game.tiles.filter(t=>!game.validate('cannon',t.x,t.z)).map(t=>({tile:t,screen:world.project(t.x,t.z)})).find(p=>{
      const q=world.pick(p.screen.x,p.screen.y);
      return q?.x===p.tile.x&&q?.z===p.tile.z&&p.screen.y>160&&p.screen.y<innerHeight-290&&document.elementFromPoint(p.screen.x,p.screen.y)===world.renderer.domElement;
    });
  });
  assert.ok(placementCell);
  const card=await page.locator('[data-tool=cannon]').boundingBox();
  await page.mouse.move(card.x+card.width/2,card.y+card.height/2);await page.mouse.down();
  await page.mouse.move(placementCell.screen.x,placementCell.screen.y,{steps:12});await page.mouse.up();
  assert.equal(await page.evaluate(()=>window.__riverwatch.placement.dragging),false);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),380);
  await page.locator('#placement-right').click();
  await page.locator('#placement-cancel').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),380);
  assert.equal(await page.evaluate(()=>window.__riverwatch.world.ghost===null),true);
  await page.locator('[data-tool=cannon]').click();
  await page.mouse.click(placementCell.screen.x,placementCell.screen.y);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),255);
  assert.equal(await page.evaluate(()=>window.__riverwatch.world.ghost===null),true);
  assert.equal(await page.evaluate(()=>window.__riverwatch.placement.tool),'inspect');
  await page.locator('#help').click();await page.locator('#restart-help').click();
  checks.push('card drag release is free; next click builds once, clears preview and returns to inspect');
  await page.locator('#scout-callout').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.paused),true);
  assert.equal(await page.locator('.scout-enemy b').textContent(),'？？？');
  assert.equal(await page.locator('.scout-enemy strong').textContent(),'× 12');
  assert.equal(await page.locator('.scout-enemy .enemy-portrait').count(),0);
  await page.locator('#scout-back').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.paused),false);
  assert.equal(await page.locator('[data-outpost="westfield"]').isVisible(),false);
  await page.locator('#estate-open').click();
  await page.locator('#restore-outpost').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),290);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.outposts[0].owned),true);
  await page.locator('#upgrade-outpost').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.outposts[0].level),2);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),150);
  await page.locator('#close-selection').click();
  await page.locator('#map-select').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.paused),true);
  await page.locator('#atlas-resume').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.outposts[0].owned),true);
  assert.ok((await page.locator('#wave-briefing').textContent()).includes('西岸'));
  await page.locator('#start-wave').click();
  await page.waitForFunction(()=>window.__riverwatch.game.enemies.length>0);
  await page.locator('#pause').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.paused),true);
  await page.locator('.intel-open').waitFor({state:'visible'});
  assert.ok((await page.locator('.intel-open').textContent()).includes('本关首次登场'));
  await page.locator('.intel-open').click();
  await page.locator('.bestiary-close').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.paused),true);
  await page.locator('#scout-callout').click();
  assert.ok((await page.locator('.scout-fronts').textContent()).includes('林地地精'));
  assert.ok((await page.locator('.scout-fronts').textContent()).includes('？？？'));
  await page.screenshot({path:'.playwright/windford-scouts.png'});
  await page.locator('#scout-back').click();
  await page.screenshot({path:'.playwright/windford-battle.png'});
  checks.push('Windford deployment, production investment, resume, wave briefing and pause');
  await page.locator('#help').click();await page.locator('#restart-help').click();
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.wave),0);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.resources.gold),380);
  assert.equal(await page.evaluate(()=>window.__riverwatch.game.outposts.some(p=>p.owned)),false);
  await page.locator('#start-wave').click();
  await page.locator('.intel-open').waitFor({state:'visible'});
  assert.ok((await page.locator('.intel-open').textContent()).includes('林地地精'));
  await page.locator('#pause').click();
  checks.push('scouting hides unknown types, identifies encountered types, restores pause, and repeats first-encounter alerts on replay');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.locator('.objective h2').isVisible(),false);
  await page.locator('#estate-open').click();
  await page.locator('[data-estate=northmine]').click();
  assert.ok((await page.locator('#selection').textContent()).includes('北坡银矿'));
  await page.locator('#close-selection').click();
  await page.locator('#scout-callout').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'.playwright/windford-scouts-mobile.png'});
  await page.locator('#scout-back').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'.playwright/windford-mobile.png'});
  await page.locator('#map-select').click();
  await page.screenshot({path:'.playwright/campaign-mobile.png'});
  checks.push('restart resets production and battle; mobile layout remains within viewport');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({checks,errors},null,2));
} finally { await browser.close(); }
